version: "3"
services:
  moloch:
    image: sdygt/moloch-docker:latest
    volumes:
      - moloch_raw_pcap:/data/moloch/raw
    depends_on:
      - elasticsearch
    environment:
      - MOLOCH_ELASTICSEARCH=elasticsearch:9200
    ports:
      - "8005:8005"
    restart: unless-stopped
  elasticsearch:
    image: elasticsearch
    expose:
      - "9200"
    restart: unless-stopped
volumes:
  moloch_raw_pcap: